/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as authenticatedProfileRouteImport } from './routes/(authenticated)/profile'
import { Route as authenticatedFeedbackRouteImport } from './routes/(authenticated)/feedback'
import { Route as authenticatedChatRouteImport } from './routes/(authenticated)/chat'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authLogInRouteImport } from './routes/(auth)/log-in'
import { Route as authenticatedAdminRouteRouteImport } from './routes/(authenticated)/admin/route'
import { Route as publicBlogsIndexRouteImport } from './routes/(public)/blogs/index'
import { Route as authenticatedAdminProfileRouteImport } from './routes/(authenticated)/admin/profile'
import { Route as authAdminSignUpRouteImport } from './routes/(auth)/admin/sign-up'
import { Route as authAdminLogInRouteImport } from './routes/(auth)/admin/log-in'
import { Route as authenticatedAdminDashboardRouteRouteImport } from './routes/(authenticated)/admin/dashboard/route'
import { Route as publicBlogsSlugIndexRouteImport } from './routes/(public)/blogs/$slug/index'
import { Route as authenticatedAdminDashboardIndexRouteImport } from './routes/(authenticated)/admin/dashboard/index'
import { Route as authenticatedChatRoomRoomIdRouteImport } from './routes/(authenticated)/chat/room/$roomId'
import { Route as authenticatedAdminDashboardTagsRouteImport } from './routes/(authenticated)/admin/dashboard/tags'
import { Route as authenticatedAdminDashboardFeedbacksRouteImport } from './routes/(authenticated)/admin/dashboard/feedbacks'
import { Route as authenticatedAdminDashboardCommentsRouteImport } from './routes/(authenticated)/admin/dashboard/comments'
import { Route as authenticatedAdminDashboardCategoriesRouteImport } from './routes/(authenticated)/admin/dashboard/categories'
import { Route as authenticatedAdminDashboardBlogsIndexRouteImport } from './routes/(authenticated)/admin/dashboard/blogs/index'
import { Route as authenticatedAdminDashboardBlogsNewRouteImport } from './routes/(authenticated)/admin/dashboard/blogs/new'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedProfileRoute = authenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedFeedbackRoute = authenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedChatRoute = authenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogInRoute = authLogInRouteImport.update({
  id: '/(auth)/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAdminRouteRoute = authenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicBlogsIndexRoute = publicBlogsIndexRouteImport.update({
  id: '/(public)/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAdminProfileRoute =
  authenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const authAdminSignUpRoute = authAdminSignUpRouteImport.update({
  id: '/(auth)/admin/sign-up',
  path: '/admin/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authAdminLogInRoute = authAdminLogInRouteImport.update({
  id: '/(auth)/admin/log-in',
  path: '/admin/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAdminDashboardRouteRoute =
  authenticatedAdminDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedAdminRouteRoute,
  } as any)
const publicBlogsSlugIndexRoute = publicBlogsSlugIndexRouteImport.update({
  id: '/(public)/blogs/$slug/',
  path: '/blogs/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAdminDashboardIndexRoute =
  authenticatedAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedChatRoomRoomIdRoute =
  authenticatedChatRoomRoomIdRouteImport.update({
    id: '/room/$roomId',
    path: '/room/$roomId',
    getParentRoute: () => authenticatedChatRoute,
  } as any)
const authenticatedAdminDashboardTagsRoute =
  authenticatedAdminDashboardTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardFeedbacksRoute =
  authenticatedAdminDashboardFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardCommentsRoute =
  authenticatedAdminDashboardCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardCategoriesRoute =
  authenticatedAdminDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardBlogsIndexRoute =
  authenticatedAdminDashboardBlogsIndexRouteImport.update({
    id: '/blogs/',
    path: '/blogs/',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)
const authenticatedAdminDashboardBlogsNewRoute =
  authenticatedAdminDashboardBlogsNewRouteImport.update({
    id: '/blogs/new',
    path: '/blogs/new',
    getParentRoute: () => authenticatedAdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/log-in': typeof authLogInRoute
  '/sign-up': typeof authSignUpRoute
  '/chat': typeof authenticatedChatRouteWithChildren
  '/feedback': typeof authenticatedFeedbackRoute
  '/profile': typeof authenticatedProfileRoute
  '/about': typeof publicAboutRoute
  '/admin/dashboard': typeof authenticatedAdminDashboardRouteRouteWithChildren
  '/admin/log-in': typeof authAdminLogInRoute
  '/admin/sign-up': typeof authAdminSignUpRoute
  '/admin/profile': typeof authenticatedAdminProfileRoute
  '/blogs': typeof publicBlogsIndexRoute
  '/admin/dashboard/categories': typeof authenticatedAdminDashboardCategoriesRoute
  '/admin/dashboard/comments': typeof authenticatedAdminDashboardCommentsRoute
  '/admin/dashboard/feedbacks': typeof authenticatedAdminDashboardFeedbacksRoute
  '/admin/dashboard/tags': typeof authenticatedAdminDashboardTagsRoute
  '/chat/room/$roomId': typeof authenticatedChatRoomRoomIdRoute
  '/admin/dashboard/': typeof authenticatedAdminDashboardIndexRoute
  '/blogs/$slug': typeof publicBlogsSlugIndexRoute
  '/admin/dashboard/blogs/new': typeof authenticatedAdminDashboardBlogsNewRoute
  '/admin/dashboard/blogs': typeof authenticatedAdminDashboardBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/log-in': typeof authLogInRoute
  '/sign-up': typeof authSignUpRoute
  '/chat': typeof authenticatedChatRouteWithChildren
  '/feedback': typeof authenticatedFeedbackRoute
  '/profile': typeof authenticatedProfileRoute
  '/about': typeof publicAboutRoute
  '/admin/log-in': typeof authAdminLogInRoute
  '/admin/sign-up': typeof authAdminSignUpRoute
  '/admin/profile': typeof authenticatedAdminProfileRoute
  '/blogs': typeof publicBlogsIndexRoute
  '/admin/dashboard/categories': typeof authenticatedAdminDashboardCategoriesRoute
  '/admin/dashboard/comments': typeof authenticatedAdminDashboardCommentsRoute
  '/admin/dashboard/feedbacks': typeof authenticatedAdminDashboardFeedbacksRoute
  '/admin/dashboard/tags': typeof authenticatedAdminDashboardTagsRoute
  '/chat/room/$roomId': typeof authenticatedChatRoomRoomIdRoute
  '/admin/dashboard': typeof authenticatedAdminDashboardIndexRoute
  '/blogs/$slug': typeof publicBlogsSlugIndexRoute
  '/admin/dashboard/blogs/new': typeof authenticatedAdminDashboardBlogsNewRoute
  '/admin/dashboard/blogs': typeof authenticatedAdminDashboardBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteRouteWithChildren
  '/(auth)/log-in': typeof authLogInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(authenticated)/chat': typeof authenticatedChatRouteWithChildren
  '/(authenticated)/feedback': typeof authenticatedFeedbackRoute
  '/(authenticated)/profile': typeof authenticatedProfileRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/admin/dashboard': typeof authenticatedAdminDashboardRouteRouteWithChildren
  '/(auth)/admin/log-in': typeof authAdminLogInRoute
  '/(auth)/admin/sign-up': typeof authAdminSignUpRoute
  '/(authenticated)/admin/profile': typeof authenticatedAdminProfileRoute
  '/(public)/blogs/': typeof publicBlogsIndexRoute
  '/(authenticated)/admin/dashboard/categories': typeof authenticatedAdminDashboardCategoriesRoute
  '/(authenticated)/admin/dashboard/comments': typeof authenticatedAdminDashboardCommentsRoute
  '/(authenticated)/admin/dashboard/feedbacks': typeof authenticatedAdminDashboardFeedbacksRoute
  '/(authenticated)/admin/dashboard/tags': typeof authenticatedAdminDashboardTagsRoute
  '/(authenticated)/chat/room/$roomId': typeof authenticatedChatRoomRoomIdRoute
  '/(authenticated)/admin/dashboard/': typeof authenticatedAdminDashboardIndexRoute
  '/(public)/blogs/$slug/': typeof publicBlogsSlugIndexRoute
  '/(authenticated)/admin/dashboard/blogs/new': typeof authenticatedAdminDashboardBlogsNewRoute
  '/(authenticated)/admin/dashboard/blogs/': typeof authenticatedAdminDashboardBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/chat'
    | '/feedback'
    | '/profile'
    | '/about'
    | '/admin/dashboard'
    | '/admin/log-in'
    | '/admin/sign-up'
    | '/admin/profile'
    | '/blogs'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/comments'
    | '/admin/dashboard/feedbacks'
    | '/admin/dashboard/tags'
    | '/chat/room/$roomId'
    | '/admin/dashboard/'
    | '/blogs/$slug'
    | '/admin/dashboard/blogs/new'
    | '/admin/dashboard/blogs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/chat'
    | '/feedback'
    | '/profile'
    | '/about'
    | '/admin/log-in'
    | '/admin/sign-up'
    | '/admin/profile'
    | '/blogs'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/comments'
    | '/admin/dashboard/feedbacks'
    | '/admin/dashboard/tags'
    | '/chat/room/$roomId'
    | '/admin/dashboard'
    | '/blogs/$slug'
    | '/admin/dashboard/blogs/new'
    | '/admin/dashboard/blogs'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/admin'
    | '/(auth)/log-in'
    | '/(auth)/sign-up'
    | '/(authenticated)/chat'
    | '/(authenticated)/feedback'
    | '/(authenticated)/profile'
    | '/(public)/about'
    | '/(public)/'
    | '/(authenticated)/admin/dashboard'
    | '/(auth)/admin/log-in'
    | '/(auth)/admin/sign-up'
    | '/(authenticated)/admin/profile'
    | '/(public)/blogs/'
    | '/(authenticated)/admin/dashboard/categories'
    | '/(authenticated)/admin/dashboard/comments'
    | '/(authenticated)/admin/dashboard/feedbacks'
    | '/(authenticated)/admin/dashboard/tags'
    | '/(authenticated)/chat/room/$roomId'
    | '/(authenticated)/admin/dashboard/'
    | '/(public)/blogs/$slug/'
    | '/(authenticated)/admin/dashboard/blogs/new'
    | '/(authenticated)/admin/dashboard/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  authLogInRoute: typeof authLogInRoute
  authSignUpRoute: typeof authSignUpRoute
  publicAboutRoute: typeof publicAboutRoute
  publicIndexRoute: typeof publicIndexRoute
  authAdminLogInRoute: typeof authAdminLogInRoute
  authAdminSignUpRoute: typeof authAdminSignUpRoute
  publicBlogsIndexRoute: typeof publicBlogsIndexRoute
  publicBlogsSlugIndexRoute: typeof publicBlogsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/profile': {
      id: '/(authenticated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/feedback': {
      id: '/(authenticated)/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof authenticatedFeedbackRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/chat': {
      id: '/(authenticated)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof authenticatedChatRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/log-in': {
      id: '/(auth)/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof authLogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/blogs/': {
      id: '/(public)/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof publicBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/profile': {
      id: '/(authenticated)/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof authenticatedAdminProfileRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(auth)/admin/sign-up': {
      id: '/(auth)/admin/sign-up'
      path: '/admin/sign-up'
      fullPath: '/admin/sign-up'
      preLoaderRoute: typeof authAdminSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/admin/log-in': {
      id: '/(auth)/admin/log-in'
      path: '/admin/log-in'
      fullPath: '/admin/log-in'
      preLoaderRoute: typeof authAdminLogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/dashboard': {
      id: '/(authenticated)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof authenticatedAdminDashboardRouteRouteImport
      parentRoute: typeof authenticatedAdminRouteRoute
    }
    '/(public)/blogs/$slug/': {
      id: '/(public)/blogs/$slug/'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof publicBlogsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/dashboard/': {
      id: '/(authenticated)/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof authenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/chat/room/$roomId': {
      id: '/(authenticated)/chat/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/chat/room/$roomId'
      preLoaderRoute: typeof authenticatedChatRoomRoomIdRouteImport
      parentRoute: typeof authenticatedChatRoute
    }
    '/(authenticated)/admin/dashboard/tags': {
      id: '/(authenticated)/admin/dashboard/tags'
      path: '/tags'
      fullPath: '/admin/dashboard/tags'
      preLoaderRoute: typeof authenticatedAdminDashboardTagsRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard/feedbacks': {
      id: '/(authenticated)/admin/dashboard/feedbacks'
      path: '/feedbacks'
      fullPath: '/admin/dashboard/feedbacks'
      preLoaderRoute: typeof authenticatedAdminDashboardFeedbacksRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard/comments': {
      id: '/(authenticated)/admin/dashboard/comments'
      path: '/comments'
      fullPath: '/admin/dashboard/comments'
      preLoaderRoute: typeof authenticatedAdminDashboardCommentsRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard/categories': {
      id: '/(authenticated)/admin/dashboard/categories'
      path: '/categories'
      fullPath: '/admin/dashboard/categories'
      preLoaderRoute: typeof authenticatedAdminDashboardCategoriesRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard/blogs/': {
      id: '/(authenticated)/admin/dashboard/blogs/'
      path: '/blogs'
      fullPath: '/admin/dashboard/blogs'
      preLoaderRoute: typeof authenticatedAdminDashboardBlogsIndexRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
    '/(authenticated)/admin/dashboard/blogs/new': {
      id: '/(authenticated)/admin/dashboard/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/dashboard/blogs/new'
      preLoaderRoute: typeof authenticatedAdminDashboardBlogsNewRouteImport
      parentRoute: typeof authenticatedAdminDashboardRouteRoute
    }
  }
}

interface authenticatedAdminDashboardRouteRouteChildren {
  authenticatedAdminDashboardCategoriesRoute: typeof authenticatedAdminDashboardCategoriesRoute
  authenticatedAdminDashboardCommentsRoute: typeof authenticatedAdminDashboardCommentsRoute
  authenticatedAdminDashboardFeedbacksRoute: typeof authenticatedAdminDashboardFeedbacksRoute
  authenticatedAdminDashboardTagsRoute: typeof authenticatedAdminDashboardTagsRoute
  authenticatedAdminDashboardIndexRoute: typeof authenticatedAdminDashboardIndexRoute
  authenticatedAdminDashboardBlogsNewRoute: typeof authenticatedAdminDashboardBlogsNewRoute
  authenticatedAdminDashboardBlogsIndexRoute: typeof authenticatedAdminDashboardBlogsIndexRoute
}

const authenticatedAdminDashboardRouteRouteChildren: authenticatedAdminDashboardRouteRouteChildren =
  {
    authenticatedAdminDashboardCategoriesRoute:
      authenticatedAdminDashboardCategoriesRoute,
    authenticatedAdminDashboardCommentsRoute:
      authenticatedAdminDashboardCommentsRoute,
    authenticatedAdminDashboardFeedbacksRoute:
      authenticatedAdminDashboardFeedbacksRoute,
    authenticatedAdminDashboardTagsRoute: authenticatedAdminDashboardTagsRoute,
    authenticatedAdminDashboardIndexRoute:
      authenticatedAdminDashboardIndexRoute,
    authenticatedAdminDashboardBlogsNewRoute:
      authenticatedAdminDashboardBlogsNewRoute,
    authenticatedAdminDashboardBlogsIndexRoute:
      authenticatedAdminDashboardBlogsIndexRoute,
  }

const authenticatedAdminDashboardRouteRouteWithChildren =
  authenticatedAdminDashboardRouteRoute._addFileChildren(
    authenticatedAdminDashboardRouteRouteChildren,
  )

interface authenticatedAdminRouteRouteChildren {
  authenticatedAdminDashboardRouteRoute: typeof authenticatedAdminDashboardRouteRouteWithChildren
  authenticatedAdminProfileRoute: typeof authenticatedAdminProfileRoute
}

const authenticatedAdminRouteRouteChildren: authenticatedAdminRouteRouteChildren =
  {
    authenticatedAdminDashboardRouteRoute:
      authenticatedAdminDashboardRouteRouteWithChildren,
    authenticatedAdminProfileRoute: authenticatedAdminProfileRoute,
  }

const authenticatedAdminRouteRouteWithChildren =
  authenticatedAdminRouteRoute._addFileChildren(
    authenticatedAdminRouteRouteChildren,
  )

interface authenticatedChatRouteChildren {
  authenticatedChatRoomRoomIdRoute: typeof authenticatedChatRoomRoomIdRoute
}

const authenticatedChatRouteChildren: authenticatedChatRouteChildren = {
  authenticatedChatRoomRoomIdRoute: authenticatedChatRoomRoomIdRoute,
}

const authenticatedChatRouteWithChildren =
  authenticatedChatRoute._addFileChildren(authenticatedChatRouteChildren)

interface authenticatedRouteRouteChildren {
  authenticatedAdminRouteRoute: typeof authenticatedAdminRouteRouteWithChildren
  authenticatedChatRoute: typeof authenticatedChatRouteWithChildren
  authenticatedFeedbackRoute: typeof authenticatedFeedbackRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAdminRouteRoute: authenticatedAdminRouteRouteWithChildren,
  authenticatedChatRoute: authenticatedChatRouteWithChildren,
  authenticatedFeedbackRoute: authenticatedFeedbackRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  authLogInRoute: authLogInRoute,
  authSignUpRoute: authSignUpRoute,
  publicAboutRoute: publicAboutRoute,
  publicIndexRoute: publicIndexRoute,
  authAdminLogInRoute: authAdminLogInRoute,
  authAdminSignUpRoute: authAdminSignUpRoute,
  publicBlogsIndexRoute: publicBlogsIndexRoute,
  publicBlogsSlugIndexRoute: publicBlogsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
